// Auto-generated by `cargo run --bin fetch_sizes`. Do not edit.
// Run `cargo run --bin fetch_sizes -- --dirs-only` to populate this file.

use std::collections::HashMap;
use std::ops::Range;
use std::sync::OnceLock;

/// (name, href, size, date, is_folder, parent_path)
pub static DIR_ENTRIES: &[(&str,&str,&str,&str,bool,&str); 0] = &[];

static DIR_INDEX_LOCK: OnceLock<HashMap<&'static str, Range<usize>>> = OnceLock::new();

pub fn dir_index() -> &'static HashMap<&'static str, Range<usize>> {
    DIR_INDEX_LOCK.get_or_init(HashMap::new)
}
